# Generated by Django 3.2 on 2023-10-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblProfesor',
            fields=[
                ('profesor_id', models.AutoField(primary_key=True, serialize=False)),
                ('profesor_nombre', models.CharField(max_length=255)),
                ('profesor_email', models.CharField(max_length=255)),
            ],
        ),
    ]
