# Generated by Django 3.2 on 2023-10-18 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_tblprofesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('CodCurso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('credito', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('codDocente', models.AutoField(primary_key=True, serialize=False)),
                ('apeliido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8)),
                ('telefono', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('CodEstudiante', models.AutoField(primary_key=True, serialize=False)),
                ('anioingreso', models.DateTimeField(verbose_name='published')),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='MatriculaU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anioacademico', models.DateTimeField(verbose_name='published')),
                ('ciclo', models.CharField(max_length=10)),
                ('fecha', models.DateTimeField(verbose_name='published')),
                ('codigocurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.curso')),
                ('codigodocente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.docente')),
                ('codigoestudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.estudiante')),
            ],
        ),
        migrations.DeleteModel(
            name='TblAlumno',
        ),
        migrations.DeleteModel(
            name='TblProfesor',
        ),
    ]
