# Generated by Django 3.2 on 2023-10-18 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20231018_1606'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatriculaU',
            new_name='Matricula',
        ),
    ]
