# Generated by Django 3.2 on 2023-10-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20231018_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='dni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='docente',
            name='telefono',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='ciclo',
            field=models.IntegerField(),
        ),
    ]
