# Generated by Django 3.2 on 2023-10-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20231018_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='anioacademico',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='fecha',
            field=models.DateField(),
        ),
    ]
