# Generated by Django 3.2 on 2023-10-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_estudiante_anioingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='anioacademico',
            field=models.DateField(verbose_name='Año académico'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='ciclo',
            field=models.CharField(max_length=2),
        ),
    ]
