# Generated by Django 3.2 on 2023-11-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20231018_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='fecha',
            field=models.DateField(verbose_name='Fecha de matrícula'),
        ),
    ]
